### ISSUE TITLE
Ne démarre pas : conf systemd NOK

### ISSUE THREAD

**Issue by anubister** [anubister/domoticz_ynh#1]
Après l'installation, domoticz n'est pas démarré, `service domoticz start` ne permet pas de démarrer.

Le port n'est pas configuré correctement dans le service systemd :
`/etc/systemd/system/domoticz.service`
Éditer le fichier et remplacer `__PORT__` par `8080`.

**Comment by bendia-** [comment]
Sur IRC, Aleks m'a mis sur la piste pour corriger le problème. Il fallait également ajouter une commande pour lancer le service. J'ai donc fait une PR.

J'en ai profiter pour ajouter une option au lanceur afin de désactiver la mise à jour automatique qui pose forcement un problème. L'archive de Domoticz, qui a systématiquement une version majeure de retard, donc, même si on installe la dernière version à jour, ça demande nécessairement une mise à jour.
