### ISSUE TITLE
maj vers version plus récente

### ISSUE THREAD

**Issue by anubister** [anubister/domoticz_ynh#6]
à partir de la version 2020.1 Domoticz requiert CMake >= 3.16 mais Debian 10 ne fournit que la version 3.13.
C'est pourquoi actuellement la version de Domoticz fournie ne peut pas être mise à jour.
Voir pour installer version spécifique sans casser les autres app qui ont besoin de CMake.
Contribution bienvenue.

**Comment by Krakinou** [comment]
Hello,
J'ai commencé à packager l'app également et j'ai utilisé une technique complètement différente de la tienne pour installer l'app : plutot que de compiler à partir des sources, je me suis inspiré du script d'install "classique" pour télécharger la dernière version stable du programme depuis le repo de domoticz https://releases.domoticz.com/releases/?dir=release.
Chez moi l'install prend à peine une minute et pas besoin de compiler.

Je viens de pousser mon package sur github ici : 
https://github.com/Krakinou/domoticz_ynh

Il me reste encore du paufinage (le readme, la licence, le changeurl, etc) et trouver un mécanisme pour gérer la version (le numéro de version n'est pas dans le fichier de release, mais je me demande si on ne pourrait pas passer par l'updater interne).
Pour l'instant, ma version passe la majorité des tests de package_check
N'hésite pas à me faire signe si tu souhaites que nous collaborions sur le sujet.

**Comment by anubister** [comment]
Salut,
c'est effectivement une option intéressante, en particulier pour installer sur des Raspberry.
À court terme je peux ajouter un lien vers ton projet.
On peut en discuter plus en détail sur xmpp:apps@conference.yunohost.org?join si tu souhaites.

**Comment by anubister** [comment]
Du coup résolu avec la nouvelle app de Krakinou disponible ici : https://github.com/YunoHost-Apps/domoticz_ynh
